# YAML
# argocd/app-monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 62.7.0
    helm:
      releaseName: kps
      values: |
        grafana:
          adminUser: admin
          adminPassword: CHANGE_ME_SECURELY
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: [ "grafana.example.com" ]
            tls:
              - secretName: grafana-tls
                hosts: [ "grafana.example.com" ]
        prometheus:
          ingress:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true